services:
  - type: web
    name: swipeybot
    env: node
    plan: free
    buildCommand: npm install -g pnpm && pnpm install --frozen-lockfile && cd artifacts/web-client && pnpm run build && cd ../api-server && node ./build.mjs
    startCommand: node --enable-source-maps artifacts/api-server/dist/index.mjs
    healthCheckPath: /api/healthz
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: ADMIN_TELEGRAM_ID
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
      - key: TELEGRAM_GROUP_ID
        sync: false
      - key: TELEGRAM_GROUP_LINK
        sync: false
